### ISSUE TITLE
Is interval server project still active and maintained.

### ISSUE THREAD

**Issue by jraoult** [interval/server#12]
@alexarena I was looking forward to using interval.io to build some internal tools only to read via [Twitter](https://x.com/tommyjmarshall/status/1739723612184048071) that you "have been mostly focused on developing the open source version of Interval Server". That said, after checking the repo, it looks like the code was dumped into it, but nothing much happened afterwards.

So I'll be that guy on every OS repo on Github and ask what the future of the Interval server is as an OS project. Is it a good idea to start using it now, or should we try to find an alternative (which, sadly, there seems to be none)?

**Comment by alexarena** [comment]
Hi! The tl;dr is that we're still using Interval extensively at Meter (the company that acquired us), but haven't invested much into new features. I'd love to find some time to add more functionality (new I/O methods, etc.) but it hasn't been a priority while everything "just works." If the current feature set works well for your needs (or you're willing to open PRs for what's missing), I'd absolutely consider building with Interval. I'm biased but I think it's still the best way to build internal tools without worrying about building bespoke UIs 🙂 

(I'm gonna close this issue, but feel free to reopen if you'd like to discuss more.)

**Comment by jraoult** [comment]
@alexarena, thanks for the answer and it's good to know it is still actively used. I think you were onto something with Interval; it is a shame (for us) that it got acquired (happy for you, though). I would have happily paid for a managed version of it 🤷‍♂️.

I have one last question to clarify. Do you run the open-source Interval at Meteor, or do you have your private fork where you fix things in priority?

**Comment by alexarena** [comment]
We actually still use the publicly available hosted version. The plan is to switch to the open-source self-hosted version at some point though (they're functionally equivalent). No plans to do a private fork. Unless we end up needing something very unusual, I think we'd want to contribute any improvements back to the community 🙂
