### ISSUE TITLE
 help@interval.com sender address prevents email/account confirmation

### ISSUE THREAD

**Issue by redlumxn** [interval/server#2]
In order to create Organization `API Keys` the account email needs to be confirmed. As per the documentation, a Postmark API key is required in order to send the emails. However, after creating a Postmark account and setting the key to the `POSTMARK_API_KEY` env var, I get the below error.

```
While your account is pending approval, all recipient addresses must share the same domain as the 'From' address. The domain of the 'From' address is 'interval.com', but you are attempting to send email to the following domain(s): 'MYCOMPANY.com'
```

Obviously this is a limitation on Postmark, but even when if the account is approved, I don't think emails should come from an interval.com address.  It would be better to pass this as another env variable. I'm happy to submit a PR but wanted to check if there is anything else that needs to be taken into account.

This seems to be the line in question setting the from address:

https://github.com/interval/server/blob/0369bde42c7d2488234fd2f113b50817ae1d56bc/src/emails/sender.ts#L92

**Comment by jacobmischka** [comment]
Definitely an oversight on our part, this should be configurable as well.

**Comment by tonyfromundefined** [comment]
We are also trying to use interval, but are experiencing the same problem.

**Comment by alexarena** [comment]
Thanks for making the change @batuhan! Released to [npm](https://www.npmjs.com/package/@interval/server/v/1.0.3) and [Docker](https://hub.docker.com/layers/alexarena/interval-server/1.0.3/images/sha256-52c3029b1310712ca6ca78f0e2c6b3520a3c281768e64ff73b925e123dd37ab6?context=repo) as 1.0.3 🙌
